# Generated by Django 5.0.9 on 2024-10-02 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Klasse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('klasse', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Barn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navn', models.CharField(max_length=50)),
                ('klas_trin', models.CharField(max_length=10)),
                ('klasse', models.ManyToManyField(related_name='item', to='klasse.klasse')),
            ],
        ),
        migrations.CreateModel(
            name='Personale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navn', models.CharField(max_length=100)),
                ('stilling', models.CharField(max_length=50)),
                ('timer', models.CharField(max_length=10)),
                ('klasse', models.ManyToManyField(to='klasse.klasse')),
            ],
        ),
    ]
