# Generated by Django 5.0.9 on 2024-10-06 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klasse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='barn',
            name='niveau',
            field=models.CharField(choices=[(1, '1'), (2, '2'), (3, '3')], default=1, max_length=1),
        ),
    ]
