# Generated by Django 5.0.9 on 2024-10-10 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klasse', '0002_barn_niveau'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barn',
            name='niveau',
            field=models.CharField(choices=[(1, '1'), (2, '2'), (3, '3')], default=1, max_length=3),
        ),
    ]
